# Generated by Django 5.1.1 on 2024-09-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OTPCodes',
            new_name='OTPCode',
        ),
    ]
