# Generated by Django 5.1.1 on 2024-09-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0003_otpcode_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
